import Head from 'next/head';
import { IndexPageTemplate } from '@/components/templates/IndexPageTemplate';

export default function IndexPage() {
  return (
    <>
      <Head>
        <title>openai-api-develop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <IndexPageTemplate />
    </>
  )
}
